# ==========================================
# Set ONE active environment here
# Options: dev | qa | prod
# ==========================================
env=dev

# ==========================================
# All Environment URLs
# ==========================================
url.dev=https://secure2.us.rdy.ukg.dev/ta/admin.login
url.qa=https://secure3.us.rdy.ukg.qa/ta/admin.login
url.prod=https://secure3.us.rdy.ukg.com/ta/admin.login

# ==========================================
# Credentials
# ==========================================
username=admin
password=password123

# ==========================================
# Browser Settings
# ==========================================
browser=chromium
headless=true