name: Playwright Java Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Install Playwright Browsers
        run: |
          mvn exec:java \
          -D exec.mainClass=com.microsoft.playwright.CLI \
          -D exec.args="install --with-deps"

      - name: Run Tests
        run: mvn test

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
                name: playwright-screenshots
                path: screenshots/